### ISSUE TITLE
SMS kommt, dann Abbruch

### ISSUE THREAD

**Issue by wernersbacher** [farOverNinethousand/NetzclubChecker#1]
Also, klappt bei mir leider immernoch nicht :( Ich habs auch letzte Version schon versucht, da war das gleiche. Passwort habe ich mal nicht eingegeben, weil es so schön im Klartext gespeichert wird :D
```
Welcome to NetzclubChecker 0.1.1
Failed to load settings.json
First run - congratulations for using this script dear user
Please enter your phone number:
0159*******
Please enter your password for 'netzclub.net/login/':

NOTE: If you accidently added wrong information, delete the file settings.json and re-run the script to correct your mistake!
Press ENTER to start

Checking account 0159*******
[netzclub+] Checking netzclub+ account
[netzclub+]Performing full netzclub+ login
[netzclub+]Login step 1/2
[netzclub+]Login step 2/2
[netzclub+]Enter SMS verification (4 digits):
95**
[netzclub+]Login failed --> Did you enter a wrong number or a wrong SMS code?
```
Ich bekomme also eine SMS und ich bin sicher, dass ich die TAN richtig eingegeben habe, ich hab das nämlich schon bestimmt 4-5 mal gemacht.

Zeile 167 bekomme ich folgende Infos zurück:

`{"result": true, "session": "14t0knckf8kq3ene6adhc2lf8g", "type": "CheckVerificationCode", "existing_user": false}`

**Comment by farOverNinethousand** [comment]
Scheint mir ein serverseitiges Problem zu sein nach dem was wir geschrieben haben. Sprich: Selbst über die App klappt der Login nicht. Da kann wahrscheinlich nur der netzclub Support helfen.
Einen Bug im Script an dieser Stelle kann ich ausschließen.

**Comment by wernersbacher** [comment]
Zum jetzigen Zeitpunkt funktioniert ein netzclub+ Login auch nicht mit funktionierendem Account. Wenn ich den NetzclubChecker mit einer in der Vergangenheit benutzen Nummern ausführe, funktioniert alles.
