### ISSUE TITLE
Session-Erhaltung notwendig?

### ISSUE THREAD

**Issue by Romern** [farOverNinethousand/NetzclubChecker#3]
Vielen dank erstmal für das gute Skript.   
In der Readme steht:  
> Du solltest das Script 2-3x pro Tag starten um zu gewährleisten, dass deine Session aktiv bleibt.  

Verstehe ich das richtig, dass man den Bonus-Traffic nur bekommt wenn man das macht, oder wozu braucht man die Session?

**Comment by farOverNinethousand** [comment]
Hi. Bedanken kannst du dich, sobald es wirklich funktioniert, aber ich fühle mich geschmeichelt :D

Das mit dem 2-3x starten habe ich sicherheitshalber in die Anleitung geschrieben ich hatte noch nicht genügend Zeit, es ausführlich zu testen.
Es kann sein, dass 1x bereits reicht, aber wenn man das Script z.B. unter Windows in die Aufgabenplanung setzt oder auf einem Server laufen lässt sollte man es ohne viel Aufwand automatisiert mehrfach am Tag durchlaufen lassen können.

Ansonsten wird die Sessino sowieso wiederverwendet.
Würde man das nicht tun, müsste man bei jedem Durchgang erneut eine Login-SMSD eingeben ;)

Grüße

**Comment by h4nk0r** [comment]
Auch von mir danke :)

Zum Theme Session-Erhaltung, sollte man dazu die Datei automate.py im Hintergrund laufen lassen? Oder "Checker.py" mehrfach per Cron am Tag starten? Oder automate.py mehrfach am Tag via Cron starten?

Danke im Voraus :)

Grüße

**Comment by farOverNinethousand** [comment]
Danke :)
Die Automate war eine Idee von wernersbacher, die zumindest unter windows noch nicht läuft.

Die Automate würde dann immer laufen und das Haupt-Script in zufälligen Abständen starten.
Die Readme wird dazu noch aktualisiert werden.
Ich habe keine Zeit mehr für dieses kleine Projekt gefunden --> Es wird aber weitergehen, versprochen :)
EDIT

Dann kann ich dieses Issue eigentlich schließen? :D
**EDIT2

Das Issue kann offen bleiben. Das wichtigste funktioniert (bei mir) noch nicht: Das "last_active" wird durch die Script Ausführung nicht aktualisiert. Hier muss noch eine Kleinigkeit fehlen oder es gibt einen Bug ...**

**Comment by Romern** [comment]
Denke mal die werden bei dem ``UserSwipe`` API call wohl sanity checks machen, man müsste da wohl nochmal die App installieren und ein wenig traffic capturen. Z.z. wird ja nichtmal ne app id gesendet.

**Comment by farOverNinethousand** [comment]
Nein die App schickt tatsächlich nicht wirklich viele Merkmale, aber Hilfe ist natürlich willkommen ;)
Der größte Teil des App Traffics ist gleich geblieben mit dem Stand deines GISTS und das hatte ich erst gefunden nachdem ich mein Script angefangen hatte^^

**Comment by farOverNinethousand** [comment]
Soo ich melde mich nochmal,
die Netzclub App wurde eingestellt (siehe auch letztes Update der Readme dieses Projektes):
https://www.teltarif.de/netzclub-plus-app-kostenlose-datenpakete-aenderungen/news/80899.html
Damit schließe ich dieses Issue.
Entschuldigt bitte - ich habe leider nie die Zeit gefunden, das Ding wirklich ans Laufen zu bekommen, aber wie es scheint war es eh verschwendete Zeit - es hätte vielleicht 5-6 Monate was gebracht :D

Aalso - nächstes Mal entwederganz oder gar nicht^^
Gute Nacht ihr Leuts ;)
